### ISSUE TITLE
导入祈愿记录报错 `No wishlogs in the inported file`

### ISSUE THREAD

**Issue by AzusaYukina** [Scighost/Xunkong#33]
### OS Build: 
Windows 11 Pro (Microsoft Windows NT 10.0.22000.0)

### WebView2 Version:
99.0.1150.39

### App Version: 
0.1.2.0

### 错误描述:
使用[原神祈愿记录导出工具](https://github.com/biuuu/genshin-wish-export)的 json 数据，直接导入本应用报错；使用由该程序导出的 Excel 表格导入本应用亦报错

### 错误日志:
```log
[08:51:08.628] [WRN] Microsoft.EntityFrameworkCore.Model.Validation
The property '"WishEventInfo"."Rank4UpItems"' is a collection or enumeration type with a value converter but with no value comparer. Set a value comparer to ensure the collection/enumeration elements are compared correctly.
 
[08:51:08.628] [WRN] Microsoft.EntityFrameworkCore.Model.Validation
The property '"WishEventInfo"."Rank5UpItems"' is a collection or enumeration type with a value converter but with no value comparer. Set a value comparer to ensure the collection/enumeration elements are compared correctly.
 
[08:51:09.792] [VRB] Xunkong.Desktop.Services.UserSettingService
Query UserSetting by key "LastSelectGameRoleUid" with value "*********"
 
[08:51:09.798] [VRB] Xunkong.Desktop.Services.UserSettingService
Save UserSetting with key "LastSelectUserInfoUid", value *******
 
[08:51:09.800] [VRB] Xunkong.Desktop.Services.UserSettingService
Save UserSetting with key "LastSelectGameRoleUid", value *********
 
[08:51:09.801] [DBG] Xunkong.Desktop.ViewModels.UserPanelViewModel
Finish refresh all hoyolab and genshin user info.
 
[08:51:11.403] [INF] Xunkong.Desktop.Views.WindowRootView
Navigate to "WishlogSummaryPage"
 
[08:51:11.570] [VRB] Xunkong.Desktop.Services.UserSettingService
Query UserSetting by key "LastSelectedUidInWishlogSummaryPage" with value "*********"
 
[08:51:11.582] [VRB] Xunkong.Desktop.Services.UserSettingService
Save UserSetting with key "LastSelectedUidInWishlogSummaryPage", value *********
 
[08:51:19.835] [INF] Xunkong.Desktop.ViewModels.WishlogSummaryViewModel
Imported file path: ***********\gacha-list-*********.json.
 
[08:51:19.837] [INF] Xunkong.Desktop.Services.WishlogService
Start to import wishlog from json file: ***********\gacha-list-*********.json
 
[08:51:19.870] [INF] Xunkong.Desktop.Services.WishlogService
Total deserialozed wishlog count: 0
 
[08:51:19.870] [ERR] Xunkong.Desktop.ViewModels.WishlogSummaryViewModel
ImportWishlogItemsFromJsonFile
Xunkong.Core.XunkongApi.XunkongException: No wishlogs in the imported file.
   at Xunkong.Desktop.Services.WishlogService.ImportFromJsonFile(String file)
   at Xunkong.Desktop.ViewModels.WishlogSummaryViewModel.ImportWishlogItemsFromExcelOrJsonFile(IEnumerable`1 files)
 
[08:52:56.222] [INF] Xunkong.Desktop.ViewModels.WishlogSummaryViewModel
Imported file path: ***********\gacha-list-*********.json.
 
[08:52:56.222] [INF] Xunkong.Desktop.Services.WishlogService
Start to import wishlog from json file: ***********\gacha-list-*********.json
 
[08:52:56.248] [INF] Xunkong.Desktop.Services.WishlogService
Total deserialozed wishlog count: 0
 
[08:52:56.248] [ERR] Xunkong.Desktop.ViewModels.WishlogSummaryViewModel
ImportWishlogItemsFromJsonFile
Xunkong.Core.XunkongApi.XunkongException: No wishlogs in the imported file.
   at Xunkong.Desktop.Services.WishlogService.ImportFromJsonFile(String file)
   at Xunkong.Desktop.ViewModels.WishlogSummaryViewModel.ImportWishlogItemsFromExcelOrJsonFile(IEnumerable`1 files)
```

**Comment by xfl03** [comment]
简单看了一下[相关代码](https://github.com/Scighost/Xunkong/blob/1004e10283f4d73692104276176db7a49fc38c67/src/Core/Wish/JsonImporter.cs#L61-L65)，请确认JSON中含有`gacha_type`、`time`、`name`、`item_type`、`id`这五个属性。

**Comment by AzusaYukina** [comment]
即便使用符合 `UIGF` 的数据仍然提示 `Imported wishlogs have items without uid`
由于用户曾经使用的祈愿导出工具不同，所存取数据的格式也可能不同，希望本项目未来可以支持 `UIGF` 的导出格式
ref: [统一可交换祈愿记录标准](https://www.snapgenshin.com/development/StandardFormat.html#%E5%89%8D%E8%A8%80)

**Comment by TechOtakupoi233** [comment]
分享一下我的导入操作：
从Genshin-Wish-Export导出excel，然后直接导入刻晴牛杂店，再从刻晴牛杂店通过json或excel导入到寻空。

**Comment by xfl03** [comment]
> 即便使用符合 `UIGF` 的数据仍然提示 `Imported wishlogs have items without uid` 由于用户曾经使用的祈愿导出工具不同，所存取数据的格式也可能不同，希望本项目未来可以支持 `UIGF` 的导出格式 ref: [统一可交换祈愿记录标准](https://www.snapgenshin.com/development/StandardFormat.html#%E5%89%8D%E8%A8%80)

简而言之，作者尚未给寻空加UIGF格式的支持，需要转换一下（可以自己转换、也可以用刻晴牛杂店）才能导入

**Comment by AzusaYukina** [comment]
很显然，提出这个 issue 的本意也是希望可以更为方便的在不同程序之间转换，降低用户的操作难度
尽管确实可以通过第三方转换得到可用的数据，但在越来越多的类似程序出现后，单独的标准并不利于良好的发展
感谢楼上的回复，也希望如果作者看到这条 issue 可以考虑一下

**Comment by TechOtakupoi233** [comment]
> 分享一下我的导入操作： 从Genshin-Wish-Export导出excel，然后直接导入刻晴牛杂店，再从刻晴牛杂店通过json或excel导入到寻空。

这个做法导入的数据没有包含祈愿ID，这意味这如果这时使用寻空直接获取记录，寻空不会排除实际上重复的记录，而且寻空也没有提供按日期删除特定记录的功能，需要用户自己在导入寻空前移除半年内的数据（可获取范围），或是导入后直接对寻空的数据库删除记录。
