### ISSUE TITLE
【反馈】 国服官服号使用cookie登录后无法使用角色信息、旅行札记功能

### ISSUE THREAD

**Issue by Askwind** [Scighost/Xunkong#61]
### 问题描述

国服官服号，使用cookie登录后无法使用角色信息、旅行札记功能

### 复现步骤
使用cookie登录，点击角色信息、旅行札记功能 程序报错（-100）

### 预期行为

无预期

### 截图

![image](https://user-images.githubusercontent.com/13656212/160741574-43d159de-0410-4d89-9280-a7129349ee7f.png)

### 系统及寻空版本

- 系统：Windows10  家庭版 21H1
- 寻空：0.1.41

### 日志
` 
[10:46:49.908] [INF] 
2022-03-30T10:46:49.9048440+08:00
Xunkong Desktop Log Message
App Name: 寻空 预览版
App Version: 0.1.4.1
OS Version: Microsoft Windows NT 10.0.19043.0

Data Path: C:\Users\TF\Documents\Xunkong
WebView2 Version: 99.0.1150.55
Command Line: "C:\Program Files\WindowsApps\Xunkong.Desktop_0.1.4.1_x64__fyamk49073ha2\Xunkong.Desktop\Xunkong.Desktop.dll"

 
[10:46:49.975] [INF] 
Last version is 0.1.4.1.
 
[10:46:49.975] [INF] 
Last version is equal with or bigger than current version, don't need to migrate database.
 
[10:46:51.497] [INF] Xunkong.Desktop.Views.WindowRootView
Navigate to "WelcomePage" with paramter null
 
[10:46:51.503] [DBG] Xunkong.Desktop.ViewModels.UserPanelViewModel
Initlize User Panel.
 
[10:46:51.526] [VRB] Xunkong.Desktop.Services.UserSettingService
Save UserSetting with key "LastSelectUserInfoUid", value 打马赛克
 
[10:46:51.547] [VRB] Xunkong.Desktop.Services.UserSettingService
Save UserSetting with key "LastSelectGameRoleUid", value 打马赛克
 
[10:46:51.556] [DBG] Xunkong.Desktop.ViewModels.UserPanelViewModel
Start refresh all hoyolab and genshin user info.
 
[10:46:52.273] [WRN] Microsoft.EntityFrameworkCore.Model.Validation
The property '"WishEventInfo"."Rank4UpItems"' is a collection or enumeration type with a value converter but with no value comparer. Set a value comparer to ensure the collection/enumeration elements are compared correctly.
 
[10:46:52.273] [WRN] Microsoft.EntityFrameworkCore.Model.Validation
The property '"WishEventInfo"."Rank5UpItems"' is a collection or enumeration type with a value converter but with no value comparer. Set a value comparer to ensure the collection/enumeration elements are compared correctly.
 
[10:46:52.777] [INF] Xunkong.Desktop.MainWindow
Change background image:
https://file.xunkong.cc/wallpaper/[アナ] 神里綾人 [96858339_p0].webp
 
[10:46:52.820] [VRB] Xunkong.Desktop.Services.UserSettingService
Query UserSetting by key "LastSelectGameRoleUid" with value "打马赛克"
 
[10:46:52.826] [VRB] Xunkong.Desktop.Services.UserSettingService
Save UserSetting with key "LastSelectUserInfoUid", value 打马赛克
 
[10:46:52.827] [VRB] Xunkong.Desktop.Services.UserSettingService
Save UserSetting with key "LastSelectGameRoleUid", value 打马赛克
 
[10:46:52.828] [DBG] Xunkong.Desktop.ViewModels.UserPanelViewModel
Finish refresh all hoyolab and genshin user info.
 
[10:47:41.537] [INF] Xunkong.Desktop.Views.WindowRootView
Navigate to "CharacterInfoPage"
 
[10:47:42.116] [WRN] Microsoft.EntityFrameworkCore.Query
Compiling a query which loads related collections for more than one collection navigation, either via 'Include' or through projection, but no 'QuerySplittingBehavior' has been configured. By default, Entity Framework will use 'QuerySplittingBehavior.SingleQuery', which can potentially result in slow query performance. See https://go.microsoft.com/fwlink/?linkid=2134277 for more information. To identify the query that's triggering this warning call 'ConfigureWarnings(w => w.Throw(RelationalEventId.MultipleCollectionIncludeWarning))'.
 
[10:47:42.405] [ERR] Xunkong.Desktop.ViewModels.CharacterInfoViewModel
Get skill level with 甘雨 (10000037).
Xunkong.Core.Hoyolab.HoyolabException: 请先登录 (-100)
   at Xunkong.Core.Hoyolab.HoyolabClient.CommonSendAsync[T](HttpRequestMessage request)
   at Xunkong.Core.Hoyolab.HoyolabClient.GetAvatarSkillLevelAsync(UserGameRoleInfo role, Int32 characterId)
   at Xunkong.Desktop.Services.HoyolabService.GetAvatarSkillLevelAsync(UserGameRoleInfo role, Int32 characterId)
   at Xunkong.Desktop.ViewModels.CharacterInfoViewModel.GetCharacterSkillLevelAsync(CharacterInfo_Character character)
 
[10:47:57.702] [INF] Xunkong.Desktop.Views.WindowRootView
Navigate to "TravelNotesPage"
 
[10:48:55.840] [INF] Xunkong.Desktop.Views.WindowRootView
Navigate to "SettingPage"
`

**Comment by Askwind** [comment]
cookie值记录不完整，重复刷新网页重新得到cookie_token后解决
